FROM mcr.microsoft.com/azure-functions/java:3.0-java11-core-tools

ARG WORK_DIR=/workspace
ARG TARGET_DIR=${WORK_DIR}/target/azure-functions/azr-greeter-funqy

# Copy sources as the Quarkus extension is not public hence needs to be installed locally
RUN mkdir /workspace
COPY . /workspace
WORKDIR ${WORK_DIR}

# Install Quarkus Extensions
RUN mvn --settings $settingsXml clean install

# Build the example
RUN cd example \
    && mvn --settings ../$settingsXml clean package

WORKDIR ${WORK_DIR}/example

# dotnet for Kafka Libraries
ENV LD_LIBRARY_PATH=${TARGET_DIR}/bin/runtimes/linux-x64/native

CMD [ "/usr/bin/mvn", "azure-functions:run" ]